language: elixir

elixir:
  - 1.4.0

otp_release:
  - 19.2

before_install:
  - curl -o elasticsearch.deb https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/$ES_VERSION/elasticsearch-$ES_VERSION.deb
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo service elasticsearch restart

env:
  matrix:
    - ES_VERSION=1.7.6
    - ES_VERSION=2.4.3
    - ES_VERSION=5.3.0

script: mix coveralls.travis
