version: '2.1'

services:
  elasticsearch:
    image: elasticsearch:${ES_VERSION:-5.2.2}-alpine
    ports:
      - '9200'
    volumes:
      - /usr/share/elasticsearch/data

  postgres:
    image: postgres:alpine
    ports:
      - '5432'
    volumes:
      - /var/lib/postgresql/data

  test: &test
    build: .
    tty: true
    depends_on:
      - elasticsearch
      - postgres
    volumes:
      - .:/app
    environment:
      - MIX_ENV
      - TRAVIS
      - TRAVIS_JOB_ID
      - POSTGRES_HOST=postgres
      - ES_URI=http://elasticsearch:9200

  setup:
    <<: *test
    command: mix do deps.get, compile
    environment:
      - MIX_ENV=test
